**How to make arrays with NumPy?**
1. First, let's import the module using: ``` import numpy as np ```
2. Then, let's proceed making arrays. But before that, let's keep in mind, what kind of data we are going to use for our arrays.

Vector arrays are unidimensional and in Pandas' module the equivalence of these arrays are the Series. Example of this array: ``` array = [1, 2, 3, 4, 5]```

Matrices are two or multi dimensional arrays and in Panda's module the equivalence of these arrays are the DataFrames. Example of this array:
``` array_example = ([[1, 2, 3], [4, 5 ,6], [7, 8, 9]])```


**Methods used in NumPy**
The methods used in NumPy are the following: ```arange(), sort(), identity(), zeros(), eye(), etc.```. Let's see some examples on how we can use these methods:

In [9]:
# For example, instead of making a list for a series of numbers, we can use the arange() method.
import numpy as np

array_a = np.arange(0, 5)
print(array_a)

[0 1 2 3 4]


In [10]:
# Indexing and slicing in Vectors

print(array_a[2])
print(array_a[0])
print(array_a[-1])

2
0
4


**Matrix are composed of rows and columns, and unlike vectors they are multi dimensional**

In [11]:
array_b = [[1,2,3],
           [4,5,6],
           [7,8,9]]

array_b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
# Indexing and Slicing in a Matrix

print(array_b[1]) # I want get the value in indeces of row 1.
print(array_b[0][1]) # I want to get the value in the indeces of row 0 and column 1.

[4, 5, 6]
2


**Exercise 1**
1. Using arange() method create an array from 0 to 20.
2. With the array created, make five examples on how can you select certain indexes from the vector or series?

In [27]:
# 1
array_a = np.arange(0, 20)
print(array_a)

# 2
print(array_a[0:])
print(array_a[:])
print(array_a[:15])
print(array_a[ :-1])
print(array_a[-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
19


**RESHAPING ARRAYS: FROM VECTOR (ONE DIMENSIONAL) TO MATRIX (MULTI DIMENSIONAL)**

So how can we shape the vector to a matrix. First, let's look at the shape of the array using ```shape()``` method.

In [28]:
np.shape(array_a) #The result shape of this array is a Vector.

(20,)

To transform this into matrix: Let's use the method ```reshape()```.

In [29]:
np.reshape(array_a, (5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

**USING PANDAS FOR DATA MANAGEMENT**

After NumPy, let's proceed with managing datas with Pandas' library. Instead of Vectors and Matrices, here we use **Series** and **DataFrames**.

In [31]:
import pandas as pd

In [40]:
# In numpy we use arange() method to make a vector, here to make a series we use the method Series().

array_a = np.arange(0, 5)
series_1 = pd.Series(array_a, index=["a", "b", "c", "d", "e"])
print(series_1)

a    0
b    1
c    2
d    3
e    4
dtype: int64


***We can also use DICTIONARY to make a database in series**

In [45]:
array_a = {"dog":"bone", "cat":"milk", "monkey":"banana", "bird":"seed"}
series_1 = pd.Series(array_a)
print(series_1)

dog         bone
cat         milk
monkey    banana
bird        seed
dtype: object


**CREATING DATAFRAMES OR MULTIDIMENSIONAL ARRAYS.**

In [49]:
# CREATING DATA FRAMES FROM A DICTIONARY

countries = {'Name': ["America", "Spain", "Philippines", "Germany", "India"],
             'Codes': [1, 34, 63, 49, 91]}
pd.DataFrame(countries, index=["country 1", "country 2", "country 3", "country 4", "country 5"])

Name  Codes
country 1      America      1
country 2        Spain     34
country 3  Philippines     63
country 4      Germany     49
country 5        India     91

In [53]:
# UPDATING OR ADDING COLUMNS/ROWS OR DATA IN A DATAFRAME

df = pd.DataFrame(countries, index=["country 1", "country 2", "country 3", "country 4", "country 5"])
df['Population'] = [100, 450, 444, 232, 100]
print(df['Population'])
print(df)

country 1    100
country 2    450
country 3    444
country 4    232
country 5    100
Name: Population, dtype: int64
                  Name  Codes  Population
country 1      America      1         100
country 2        Spain     34         450
country 3  Philippines     63         444
country 4      Germany     49         232
country 5        India     91         100


In [54]:
# DELETION OF DATA/COLUMNS/ROWS IN A DATAFRAME

df.drop('Population', axis=1)

Name  Codes
country 1      America      1
country 2        Spain     34
country 3  Philippines     63
country 4      Germany     49
country 5        India     91